// <auto-generated />
namespace SportsData.Nhl.Query.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class manual1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(manual1));
        
        string IMigrationMetadata.Id
        {
            get { return "201312311802072_manual1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
