// <auto-generated />
namespace SportsData.Nhl.Query.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class migration3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration3));
        
        string IMigrationMetadata.Id
        {
            get { return "201401060753497_migration3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
