namespace SportsData.Nhl.Query.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class nhl : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Nhl_Games_Rtss_Summary_GoalieSummary_Home_Id", "dbo.Nhl_Games_Rtss_Summary");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Nhl_Games_Rtss_Summary_GoalieSummary_Visitor_Id", "dbo.Nhl_Games_Rtss_Summary");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary_Officials_Item", "Nhl_Games_Rtss_Summary_Officials_Id", "dbo.Nhl_Games_Rtss_Summary");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Nhl_Games_Rtss_Summary_PenaltySummary_Home_Id", "dbo.Nhl_Games_Rtss_Summary");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Nhl_Games_Rtss_Summary_PenaltySummary_Visitor_Id", "dbo.Nhl_Games_Rtss_Summary");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Nhl_Games_Rtss_Summary_PeriodSummary_Home_Id", "dbo.Nhl_Games_Rtss_Summary");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Nhl_Games_Rtss_Summary_PeriodSummary_Visitor_Id", "dbo.Nhl_Games_Rtss_Summary");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary", "PowerPlaySummary_Home_Id", "dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary", "PowerPlaySummary_Visitor_Id", "dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary_Stars_Item", "Nhl_Games_Rtss_Summary_Stars_Id", "dbo.Nhl_Games_Rtss_Summary");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary_ScoringSummary_Item", "Nhl_Games_Rtss_Summary_ScoringSummary_Id", "dbo.Nhl_Games_Rtss_Summary");
            DropIndex("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", new[] { "Nhl_Games_Rtss_Summary_GoalieSummary_Home_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", new[] { "Nhl_Games_Rtss_Summary_GoalieSummary_Visitor_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary_Officials_Item", new[] { "Nhl_Games_Rtss_Summary_Officials_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", new[] { "Nhl_Games_Rtss_Summary_PenaltySummary_Home_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", new[] { "Nhl_Games_Rtss_Summary_PenaltySummary_Visitor_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", new[] { "Nhl_Games_Rtss_Summary_PeriodSummary_Home_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", new[] { "Nhl_Games_Rtss_Summary_PeriodSummary_Visitor_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary", new[] { "PowerPlaySummary_Home_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary", new[] { "PowerPlaySummary_Visitor_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary_Stars_Item", new[] { "Nhl_Games_Rtss_Summary_Stars_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary_ScoringSummary_Item", new[] { "Nhl_Games_Rtss_Summary_ScoringSummary_Id" });
            AddColumn("dbo.Nhl_Games_Rtss_Summary", "HomePowerPlaySummary_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary", "VisitorPowerPlaySummary_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Team", c => c.String());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Date", c => c.DateTime(nullable: false));
            AddColumn("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Nhl_Games_Rtss_Summary_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_GoaliePeriodSummary_Item", "Team", c => c.String());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_GoaliePeriodSummary_Item", "Date", c => c.DateTime(nullable: false));
            AddColumn("dbo.Nhl_Games_Rtss_Summary_Officials_Item", "VisitorTeam", c => c.String());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_Officials_Item", "HomeTeam", c => c.String());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_Officials_Item", "Date", c => c.DateTime(nullable: false));
            AddColumn("dbo.Nhl_Games_Rtss_Summary_Officials_Item", "Nhl_Games_Rtss_Summary_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Team", c => c.String());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Date", c => c.DateTime(nullable: false));
            AddColumn("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Nhl_Games_Rtss_Summary_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Team", c => c.String());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Date", c => c.DateTime(nullable: false));
            AddColumn("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Nhl_Games_Rtss_Summary_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item", "Team", c => c.String());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item", "Date", c => c.DateTime(nullable: false));
            AddColumn("dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item", "Nhl_Games_Rtss_Summary_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_ScoringSummary_Item", "Date", c => c.DateTime(nullable: false));
            AddColumn("dbo.Nhl_Games_Rtss_Summary_ScoringSummary_Item", "Nhl_Games_Rtss_Summary_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_Stars_Item", "Date", c => c.DateTime(nullable: false));
            AddColumn("dbo.Nhl_Games_Rtss_Summary_Stars_Item", "Nhl_Games_Rtss_Summary_Id", c => c.Int());
            CreateIndex("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Nhl_Games_Rtss_Summary_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item", "Nhl_Games_Rtss_Summary_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary", "HomePowerPlaySummary_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary_Officials_Item", "Nhl_Games_Rtss_Summary_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Nhl_Games_Rtss_Summary_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Nhl_Games_Rtss_Summary_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary_Stars_Item", "Nhl_Games_Rtss_Summary_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary", "VisitorPowerPlaySummary_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary_ScoringSummary_Item", "Nhl_Games_Rtss_Summary_Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Nhl_Games_Rtss_Summary_Id", "dbo.Nhl_Games_Rtss_Summary", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item", "Nhl_Games_Rtss_Summary_Id", "dbo.Nhl_Games_Rtss_Summary", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary", "HomePowerPlaySummary_Id", "dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary_Officials_Item", "Nhl_Games_Rtss_Summary_Id", "dbo.Nhl_Games_Rtss_Summary", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Nhl_Games_Rtss_Summary_Id", "dbo.Nhl_Games_Rtss_Summary", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Nhl_Games_Rtss_Summary_Id", "dbo.Nhl_Games_Rtss_Summary", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary_Stars_Item", "Nhl_Games_Rtss_Summary_Id", "dbo.Nhl_Games_Rtss_Summary", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary", "VisitorPowerPlaySummary_Id", "dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary_ScoringSummary_Item", "Nhl_Games_Rtss_Summary_Id", "dbo.Nhl_Games_Rtss_Summary", "Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary", "PowerPlaySummary_Home_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary", "PowerPlaySummary_Visitor_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Nhl_Games_Rtss_Summary_GoalieSummary_Home_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Nhl_Games_Rtss_Summary_GoalieSummary_Visitor_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_Officials_Item", "Nhl_Games_Rtss_Summary_Officials_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Nhl_Games_Rtss_Summary_PenaltySummary_Home_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Nhl_Games_Rtss_Summary_PenaltySummary_Visitor_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Nhl_Games_Rtss_Summary_PeriodSummary_Home_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Nhl_Games_Rtss_Summary_PeriodSummary_Visitor_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_ScoringSummary_Item", "Nhl_Games_Rtss_Summary_ScoringSummary_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_Stars_Item", "Nhl_Games_Rtss_Summary_Stars_Id");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Nhl_Games_Rtss_Summary_Stars_Item", "Nhl_Games_Rtss_Summary_Stars_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_ScoringSummary_Item", "Nhl_Games_Rtss_Summary_ScoringSummary_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Nhl_Games_Rtss_Summary_PeriodSummary_Visitor_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Nhl_Games_Rtss_Summary_PeriodSummary_Home_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Nhl_Games_Rtss_Summary_PenaltySummary_Visitor_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Nhl_Games_Rtss_Summary_PenaltySummary_Home_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_Officials_Item", "Nhl_Games_Rtss_Summary_Officials_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Nhl_Games_Rtss_Summary_GoalieSummary_Visitor_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Nhl_Games_Rtss_Summary_GoalieSummary_Home_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary", "PowerPlaySummary_Visitor_Id", c => c.Int());
            AddColumn("dbo.Nhl_Games_Rtss_Summary", "PowerPlaySummary_Home_Id", c => c.Int());
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary_ScoringSummary_Item", "Nhl_Games_Rtss_Summary_Id", "dbo.Nhl_Games_Rtss_Summary");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary", "VisitorPowerPlaySummary_Id", "dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary_Stars_Item", "Nhl_Games_Rtss_Summary_Id", "dbo.Nhl_Games_Rtss_Summary");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Nhl_Games_Rtss_Summary_Id", "dbo.Nhl_Games_Rtss_Summary");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Nhl_Games_Rtss_Summary_Id", "dbo.Nhl_Games_Rtss_Summary");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary_Officials_Item", "Nhl_Games_Rtss_Summary_Id", "dbo.Nhl_Games_Rtss_Summary");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary", "HomePowerPlaySummary_Id", "dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item", "Nhl_Games_Rtss_Summary_Id", "dbo.Nhl_Games_Rtss_Summary");
            DropForeignKey("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Nhl_Games_Rtss_Summary_Id", "dbo.Nhl_Games_Rtss_Summary");
            DropIndex("dbo.Nhl_Games_Rtss_Summary_ScoringSummary_Item", new[] { "Nhl_Games_Rtss_Summary_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary", new[] { "VisitorPowerPlaySummary_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary_Stars_Item", new[] { "Nhl_Games_Rtss_Summary_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", new[] { "Nhl_Games_Rtss_Summary_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", new[] { "Nhl_Games_Rtss_Summary_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary_Officials_Item", new[] { "Nhl_Games_Rtss_Summary_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary", new[] { "HomePowerPlaySummary_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item", new[] { "Nhl_Games_Rtss_Summary_Id" });
            DropIndex("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", new[] { "Nhl_Games_Rtss_Summary_Id" });
            DropColumn("dbo.Nhl_Games_Rtss_Summary_Stars_Item", "Nhl_Games_Rtss_Summary_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_Stars_Item", "Date");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_ScoringSummary_Item", "Nhl_Games_Rtss_Summary_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_ScoringSummary_Item", "Date");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item", "Nhl_Games_Rtss_Summary_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item", "Date");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item", "Team");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Nhl_Games_Rtss_Summary_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Date");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Team");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Nhl_Games_Rtss_Summary_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Date");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Team");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_Officials_Item", "Nhl_Games_Rtss_Summary_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_Officials_Item", "Date");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_Officials_Item", "HomeTeam");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_Officials_Item", "VisitorTeam");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_GoaliePeriodSummary_Item", "Date");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_GoaliePeriodSummary_Item", "Team");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Nhl_Games_Rtss_Summary_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Date");
            DropColumn("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Team");
            DropColumn("dbo.Nhl_Games_Rtss_Summary", "VisitorPowerPlaySummary_Id");
            DropColumn("dbo.Nhl_Games_Rtss_Summary", "HomePowerPlaySummary_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary_ScoringSummary_Item", "Nhl_Games_Rtss_Summary_ScoringSummary_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary_Stars_Item", "Nhl_Games_Rtss_Summary_Stars_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary", "PowerPlaySummary_Visitor_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary", "PowerPlaySummary_Home_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Nhl_Games_Rtss_Summary_PeriodSummary_Visitor_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Nhl_Games_Rtss_Summary_PeriodSummary_Home_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Nhl_Games_Rtss_Summary_PenaltySummary_Visitor_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Nhl_Games_Rtss_Summary_PenaltySummary_Home_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary_Officials_Item", "Nhl_Games_Rtss_Summary_Officials_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Nhl_Games_Rtss_Summary_GoalieSummary_Visitor_Id");
            CreateIndex("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Nhl_Games_Rtss_Summary_GoalieSummary_Home_Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary_ScoringSummary_Item", "Nhl_Games_Rtss_Summary_ScoringSummary_Id", "dbo.Nhl_Games_Rtss_Summary", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary_Stars_Item", "Nhl_Games_Rtss_Summary_Stars_Id", "dbo.Nhl_Games_Rtss_Summary", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary", "PowerPlaySummary_Visitor_Id", "dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary", "PowerPlaySummary_Home_Id", "dbo.Nhl_Games_Rtss_Summary_PowerPlaySummary_Item", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Nhl_Games_Rtss_Summary_PeriodSummary_Visitor_Id", "dbo.Nhl_Games_Rtss_Summary", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary_PeriodSummary_Item", "Nhl_Games_Rtss_Summary_PeriodSummary_Home_Id", "dbo.Nhl_Games_Rtss_Summary", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Nhl_Games_Rtss_Summary_PenaltySummary_Visitor_Id", "dbo.Nhl_Games_Rtss_Summary", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary_PenaltySummary_Item", "Nhl_Games_Rtss_Summary_PenaltySummary_Home_Id", "dbo.Nhl_Games_Rtss_Summary", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary_Officials_Item", "Nhl_Games_Rtss_Summary_Officials_Id", "dbo.Nhl_Games_Rtss_Summary", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Nhl_Games_Rtss_Summary_GoalieSummary_Visitor_Id", "dbo.Nhl_Games_Rtss_Summary", "Id");
            AddForeignKey("dbo.Nhl_Games_Rtss_Summary_GoalieSummary_Item", "Nhl_Games_Rtss_Summary_GoalieSummary_Home_Id", "dbo.Nhl_Games_Rtss_Summary", "Id");
        }
    }
}
