// <auto-generated />
namespace SportsData.Nhl.Query.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class nhl1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nhl1));
        
        string IMigrationMetadata.Id
        {
            get { return "201412090755011_nhl1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
