// <auto-generated />
namespace SportsData.Nhl.Query.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class twitteraccounts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(twitteraccounts));
        
        string IMigrationMetadata.Id
        {
            get { return "201310200123597_twitteraccounts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
