// <auto-generated />
namespace SportsData.Nhl.Query.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddPostponedGames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPostponedGames));
        
        string IMigrationMetadata.Id
        {
            get { return "201309130101013_AddPostponedGames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
