// <auto-generated />
namespace NhlStatsQuery.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AllStats : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AllStats));
        
        string IMigrationMetadata.Id
        {
            get { return "201302040732383_AllStats"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
